### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by assumptionsoup** [HiroakiMikami/atom-clang-tools-extra#13]
Errors on lint with:
```
TypeError: Cannot read property 'split' of undefined
    at Object.getClangCppFlags (C:/Users/jordan/.atom/packages/clang-tools-extra/lib/clang-tools-extra.js:95:81)
    at ClangArguments.get (C:/Users/jordan/.atom/packages/clang-tools-extra/lib/clang-arguments.js:27:34)
    at ClangTidy.update (C:/Users/jordan/.atom/packages/clang-tools-extra/lib/clang-tidy.js:40:43)
    at ClangTidyLinter.lint (C:/Users/jordan/.atom/packages/clang-tools-extra/lib/clang-tidy-linter.js:19:27)
    at Object.lint (C:/Users/jordan/.atom/packages/clang-tools-extra/lib/clang-tools-extra.js:193:50)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/jordan/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/jordan/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/jordan/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/jordan/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at EditorLinter.lint (C:/Users/jordan/.atom/packages/linter/lib/editor-linter.js:175:18)
    at Commands.lint (file:///C:/Users/jordan/.atom/packages/linter/lib/commands.coffee:60:40)
    at atom-workspace.Commands.subscriptions.add.atom.commands.add.linter:lint (file:///C:/Users/jordan/.atom/packages/linter/lib/commands.coffee:13:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\jordan\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by HiroakiMikami** [comment]
I could reproduce this problem, and fixed this.
Could you try v0.0.2?

Thank you.

**Comment by assumptionsoup** [comment]
Thanks! Looks like the plugin is working now.  Though using clang-tidy on windows seems to be a lost cause in general...  :(

**Comment by HiroakiMikami** [comment]
Thank you for reporting this issue and testing v0.0.2!
